#
# Copyright (C) 2017-2019 Dremio Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

openapi: 3.1.0
info:
  title: Shared API schemas.
  version: v4
  description: |-
    Components shared across API specs.
  x-dremio:
    protoPackage: com.dremio.api
    javaPackage: com.dremio.api
    javaOuterClass: ApiSharedProto

servers:
  - url: "api/v4"

components:
  # Response bodies.
  responses:
    # Error.
    ErrorResponse:
      description: "Error."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseContent'

  schemas:
    # Content of the error response.
    ErrorResponseContent:
      description: |
        An [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html) problem object.
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: A URI reference that identifies the error type.
          examples:
            - "https://api.dremio.dev/problems/auth/token-invalid"
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server
            for this occurrence of the error.
          minimum: 100
          maximum: 599
        title:
          type: string
          description: A human-readable summary of the error type.
      required:
        - status
        - type

    # This schema may be returned instead of ErrorResponseContent. Oneof semantics
    # of Open API spec and Java code generator are not compatible. Also, neither
    # immutables nor protobufs support inheritance.
    ValidationErrorResponseContent:
      allOf:
        - $ref: '#/components/schemas/ErrorResponseContent'
        - type: object
          properties:
            errors:
              type: array
              description: An extension containing multiple validation or request errors.
              items:
                $ref: "#/components/schemas/Error"
          required:
            - type
            - errors

    Error:
      type: object
      description: |
        Error description with pointer to a problem field.
      properties:
        type:
          type: string
          format: uri-reference
          description: |
            A URI reference that identifies the error type.
        pointer:
          type: string
          description: |
            A JSON pointer to locate the problem within the request's content.
        detail:
          type: string
          description: A human-readable summary of the error.
